### ISSUE TITLE
Would 'superclass' be a better name?

### ISSUE THREAD

**Issue by neilb** [dagolden/superclass#1]
First: I like this module!

In writing about base, parent and inherit, I realised that the name was slightly bugging me:
base and parent are nouns, but inherit is a verb, so saying 'use inherit' doesn't scan right.

How about renaming it 'superclass'?

**Comment by dagolden** [comment]
It's long but maybe that's OK if it scans better.  I'll consider it.

On Sun, Feb 24, 2013 at 9:51 AM, neilbowers notifications@github.comwrote:

> First: I like this module!
> 
> In writing about base, parent and inherit, I realised that the name was
> slightly bugging me:
> base and parent are nouns, but inherit is a verb, so saying 'use inherit'
> doesn't scan right.
> 
> How about renaming it 'superclass'?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dagolden/inherit/issues/1.

## 

_David Golden_ dagolden@cpan.org
_Take back your inbox!_ → http://www.bunchmail.com/
Twitter/IRC: @xdg

**Comment by dagolden** [comment]
Done and shipped.

**Comment by neilb** [comment]
Awesome. That was quick!
[quick changes to article]
