### ISSUE TITLE
Will not install on Perl 5.8 with recent releases of version.pm

### ISSUE THREAD

**Issue by tobyink** [dagolden/superclass#2]
It seems that the PP edition of version.pm has [introduced a new error message](https://metacpan.org/diff/file?target=JPEACOCK/version-0.9905/&source=JPEACOCK/version-0.9904/#vperl/vpp.pm) in 0.9905.

> Invalid version format (non-numeric data)

This is intended to be omitted when an arrayref or hashref is used as a version number. superclass.pm seems to be triggering this fairly consistently in `t/version-check.t`. (Aside: not completely sure why! You don't seem to ever use arrayrefs or hashrefs as version numbers.) And this causes test 'fail v-string version check' to fail, because `$@` is the error message quoted above, so doesn't match `qr/this is only/`.

This has caused [lots of test failures on Perl 5.8 since January 2014](http://matrix.cpantesters.org/?dist=superclass+0.002). (Virtually all the passes for Perl 5.8 date from 2013.)

**Comment by dagolden** [comment]
No, that error message is triggering because it can't handle a v-string for some reason:

```
$ PERL5OPT=-MTest::NoXS=version::vxs perl -wle 'use version; $v=version->new(v1.1); print $v'
Invalid version format (non-numeric data) at -e line 1.
```

That's a version.pm bug.  I'm not sure whether to get it fixed or hack around it.

**Comment by dagolden** [comment]
Bug report filed: https://rt.cpan.org/Ticket/Display.html?id=93715

(This might even have been my own bug, since I wrote a bunch of the vpp v-string heuristics.)

**Comment by tobyink** [comment]
Thanks for working around this issue. [Positive test results are coming in](http://217.199.168.174/cgi-bin/cpantestersmatrix.pl?dist=superclass), so I consider this resolved.
